"""empty message

Revision ID: a86769ac3b60
Revises: c8388563fcd6
Create Date: 2023-01-31 21:26:54.734226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a86769ac3b60"
down_revision = "c8388563fcd6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shows", schema=None) as batch_op:
        batch_op.drop_column("name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shows", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
